config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
  	 collection do
      get 'todolist_search'
      get 'search'
    end
  	resources :tasks, only: [:create, :destroy]
  end
  post '/lists/:list_id/tasks/:id/toggle' => 'tasks#toggle'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	has_many :tasks, -> { order(created_at: :desc) }, dependent: :destroy
	validates :title, presence: true, uniqueness: true, length: { maximum: 31 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :title, presence: true, length: { maximum: 31 }, uniqueness: {scope: [:list_id]}
  validates :list_id, presence: true
  scope :finished, -> { where(done: true) }
  scope :unfinished, -> { where(done: false) }
  scope :near_deadline, -> { reorder("deadline < '#{Date.today}'") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  	@list = List.new 
  	@lists = List.includes(:tasks).order("tasks.created_at desc")
  end

  def new 
  	@list = List.new 
  end

  def show
  	@list = List.find(params[:id])
  end

  def create
  	@list = List.new(list_params)
  	if @list.save
  		flash[:success] = "新しいToDoリストが作成されました"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_url
  end

  def todolist_search
  end

  def search
    @lists = List.where('title LIKE(?)', "%#{params[:keyword]}%"), Task.where('title LIKE(?)', "%#{params[:keyword]}%")
    render json:  @lists
  end

  private

  	def list_params
  		params.require(:list).permit(:title)
  	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
      @list = List.find(params[:list_id])
      @task = @list.tasks.create(task_params)
      if @task.new_record?
        redirect_to list_path(@list.id)
        flash[:danger] = @task.errors.messages[:title][0]
      else
        redirect_to list_path(@list.id)
      end 
  end


  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(params[:list_id])
  end

  def toggle
    render body: nil
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end

  private

  def task_params
      params[:task].permit(:title, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

<script> 
    setTimeout(function(){ 
    $('.alert-success').fadeOut(); 
    }, 1000); 
</script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form_list.html.erb
<%= form_for(@list) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
		<div class="field">
			<%= f.text_field :title, placeholder: 'リスト名を入力してください', class: 'form-control' %>
		</div>
		<div class="submit">
			<%= f.submit "リストの作成", class: 'btn btn-primary' %>
		</div>
<% end %>

app/views/lists/_form_task.html.erb
<%= form_for [@list, @list.tasks.build] do |f| %>
			<p>ToDo名</p>
			<div class="field">
		    <%= f.text_field :title, class: 'form-control' %>
		  </div>
			<p>期限</p>
	    <div class="field">
	    	<%= f.date_select :deadline, class: 'form-control' %>
	    </div>
	    <%= f.submit "ToDoの追加", class: 'btn btn-primary' %>
<% end %>

app/views/lists/index.html.erb
<div id="list_form">
	<p>新しいToDoリストを作成する</p>
	<%= render 'form_list' %>
</div>

<ol class="list">
	<% @lists.each do |list| %>
		<li class="lists">
			<%= link_to list.title, list_path(list.id) %>
			<% if list.tasks.count == 0 %>
				<p>ToDoがありません</p>
			<% else %>
				<p>
					<%= list.tasks.count %>個中<%= list.tasks.finished.count %>個がチェック済み
				</p>
				<% if list.tasks.unfinished.near_deadline.first.nil? %>
					<p>期限はありません</p>
				<% else %>
					<p>
						~<%= list.tasks.unfinished.near_deadline.last.deadline.in_time_zone('Tokyo').strftime('%Y年%m月%d日') %>
					</p>
				<% end %>
			<% end %>
			<%= link_to "削除", list_path(list.id), method: :delete, data: { confirm: "削除しますか？" } %>
		</li>
	<% end %>
</ol>

app/views/lists/new.html.erb
<div class="list_form">
	<p>新しいToDoリストを作成する</p>
	<%= render 'form_list' %>	
</div>

app/views/lists/show.html.erb
<h1 id="list_title"><%= @list.title %></h1>

<div id="new_task_form"></div>



<ul class="list">
	<% if @list.tasks.any? %>
	  <% @list.tasks.each do |task| %>
      <li class="tasks">
        <div class="details">
          <p><%= task.title %></p>
          <p>期限：　<%= task.deadline.to_s(:time_format) %></p>
          <p>作成日：<%= task.created_at.to_s(:time_format) %></p>          
        </div>

      	<label class="checkbox">
          <%= check_box_tag '', 'value', task.done, {'data-id' => task.id, 'data-list_id' => task.list_id, :class => 'done_checkbox'}  %>    
          <span class="cb change_text">未完了</span>
          <span class="cb new_text">完了</span>
        </label>
        <%= link_to "削除", list_task_path(task.list_id, task.id), method: :delete, data: { confirm: "削除しますか？" } %>
      </li>
	  <% end %>
	<% else %>
	  <p>登録されているToDoはありません</p>
	<% end %>
</ul>

<div id="task_form">
  <p>新しいToDoを作成する</p>
  <%= render 'lists/form_task' %>
</div>
<script>
  $(function(){
    $('input[type=checkbox]').click(function(){
      var idList = $(this).data('list_id'),
          idTask = $(this).data('id');
      $.post('/lists/' + idList + '/tasks/' + idTask + '/toggle');

    });
  });

	// @list.eachでbuildを上にすると空のインスタンスができてしまう。
  var form = document.getElementById('task_form')
  var nf = document.getElementById('new_task_form')
  nf.appendChild(form)


</script>


	

app/views/lists/todolist_search.html.erb
<div class="search_form">
	<p>検索したいものを入力してください</p>
	<input type="text" id="search_field" class="form-control" >
	<input type="submit" name="button1" value="検索" id="search" class="btn btn-primary" >
</div>


<ul id="result" class="list">


</ul>

<script>



$(document).on('turbolinks:load', function(){
  $(document).on('click', '#search', function(e){ 
    e.preventDefault(); 
	  var input = $.trim($('#search_field').val());
	  $.ajax({ 
	     url: './search', 
	     type: 'GET', 
	     data: {keyword:input},
	     dataType: 'json'
	  })
    .done(function(data){ 
      $('#result').find('li').remove();
      console.log(data)
      var list = data[0]
      var task = data[1]
			// function resultId(e){
			// 	var s = e.currentTarget()
			// 	var i = 
			// }
      if((list.length === 0) && (task.length === 0)){
				$('#result').append('<li class="search_info">' + '対象のToDoは見つかりません' + '</li>')
				$('#result').append('<li class="search_info">' + '対象のToDoリストは見つかりません' + '</li>')
			} else if((list.length > 0) || (task.length > 0)) {
				$('#result').append('<li class="search_info">' + 'ToDoは' + task.length + '件です' + '</li>')

				for(var i=0; i < task.length; i++){
					$('#result').append(
						'<li class="tasks">'
						+ '<a href="../lists/' + task[i].list_id + '">' + task[i].title + '</a>'
						+ '<p>' + '期限：　' + createTime(task[i].deadline) + '</p>' 
					  + '<p class="create_time">' + '作成日：' + createTime(task[i].created_at) +'</p>'
						+ '</li>'
					)
	      }

				$('#result').append('<li class="search_info">' + 'ToDoリストは' + list.length + '件です' + '</li>')
	      for(var j=0; j < list.length; j++){
					$('#result').append(
						'<li class="lists">'
						+ '<a href="../lists/' + list[j].id + '">' +  list[j].title +'</a>'
						+	'<p class="create_time">' + '作成日：' + createTime(list[j].created_at) +'</p>'
						+ '</li>'	
					)
	      }
			} 
    })
  });
});

function createTime(e) {
	var t = new Date(e)
	var year = t.getFullYear()
	var month = t.getMonth() + 1
	var day = t.getDate()
	return year + '年' + month + '月' + day + '日'
}
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
   <div class="alert alert-danger">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
	<div class="container">
		<div class="header-left"><a href="/">ToDoリスト</a></div>
		<div class="header-right"><a href="../lists/todolist_search">検索</a></div>
	</div>
</header>